DROP ALL OBJECTS DELETE FILES;

CREATE TABLE IF NOT EXISTS department (
                                          dp_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                          dp_name VARCHAR(500) NOT NULL,
                                          CONSTRAINT pk_department PRIMARY KEY (dp_id)
);

CREATE TABLE IF NOT EXISTS employee (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    first_name VARCHAR(100) NOT NULL,
                                    last_name VARCHAR(100) NOT NULL,
                                    birthday TIMESTAMP NOT NULL,
									department_id BIGINT NOT NULL,
                                    salary BIGINT NOT NULL,
                                    CONSTRAINT pk_employee PRIMARY KEY (id),
                                    FOREIGN KEY (department_id) REFERENCES department (dp_id) ON DELETE CASCADE
);
